### ISSUE TITLE
是否有规划内置样式支持浅色和深色主题切换？

### ISSUE THREAD

**Issue by jujusharp** [imengyu/vue-code-layout#2]
感谢你的辛苦工作，很棒的项目，相对于其他开源的layout项目，这个项目的样式风格和复杂度我觉得是最棒的。系统内置的样式主题也很棒，不过是否可以内置深色和浅色两套主题样式支持切换？谢谢

**Comment by imengyu** [comment]
你好，暂时没有做，因为vscode的主题比较多，我做不完。不过代码中预设了可以更改颜色的方式：

https://github.com/imengyu/vue-code-layout/blob/master/library/Scss/Base.scss

所有颜色都拆分到css变量中了，你可以根据自己的配色很方便的修改变量来实现动态换色的功能。

**Comment by jujusharp** [comment]
了解了，谢谢回复
