### ISSUE TITLE
SplitLayout中的tab在超出宽度后无法横向滚动切换更多tab

### ISSUE THREAD

**Issue by jujusharp** [imengyu/vue-code-layout#7]
问题描述：
SplitLayout我可以通过添加Panel添加多个不同tab的面板，但当添加的面板数量超出面板宽度后，多出的tab不显示并且无法查看。

重现步骤：
1. 点开https://docs.imengyu.top/vue-code-layout-demo/#/SplitLayout.
2. 切换到SplitLayout示例，点击AddPanel按钮添加多个panel.
3. 多出的面板无法查看也无法切换。

期望：
期望能像vscode那样，当面板上多个tab超出宽度后，出现横向滚动条可以通过滚动鼠标切换到对应的面板。

![image](https://github.com/user-attachments/assets/be0a8210-af74-4bb6-a3bf-aa57679f5138)

**Comment by imengyu** [comment]
谢谢你的反馈，最新版本已经修改了
